parameters:
    json_api.listener.json_event_subscriber.class: Mango\Bundle\JsonApiBundle\EventListener\Serializer\JsonEventSubscriber
    jms_serializer.datetime_handler.class: Mango\Bundle\JsonApiBundle\Serializer\Handler\DateHandler

services:

    json_api.listener.json_event_subscriber:
        class: '%json_api.listener.json_event_subscriber.class%'
        arguments:
            - '@json_api.metadata_factory'
            - '@jms_serializer.metadata_factory'
            - '@jms_serializer.naming_strategy'
            - '@request_stack'
            - '@json_api.resolver.base_uri'
        tags:
            - { name: 'jms_serializer.event_subscriber' }

    json_api.serializer:
        class: 'Mango\Bundle\JsonApiBundle\Serializer\Serializer'
        decorates: 'jms_serializer.serializer'
        arguments:
            - '@json_api.serializer.inner'
            - '@json_api.serializer.relationship_exclusion_strategy'

    json_api.serializer.handler.pagerfanta:
        class: 'Mango\Bundle\JsonApiBundle\Serializer\Handler\PagerfantaHandler'
        arguments:
            - '@request_stack'
        tags:
            - { name: 'jms_serializer.subscribing_handler' }

    json_api.resolver.base_uri:
        alias: 'json_api.resolver.base_uri.default'

    json_api.resolver.base_uri.default:
        class: 'Mango\Bundle\JsonApiBundle\Resolver\BaseUri\BaseUriResolver'
        arguments:
            - '@request_stack'
            - '%json_api.base_uri%'

    jms_serializer.json_api_serialization_visitor:
        class: 'Mango\Bundle\JsonApiBundle\Serializer\JsonApiSerializationVisitor'
        arguments:
            - '@jms_serializer.naming_strategy'
            - '@jms_serializer.accessor_strategy'
            - '@json_api.metadata_factory'
            - '%json_api.show_version_info%'
        tags:
            - { name: 'jms_serializer.serialization_visitor', format: 'json:api' }

    jms_serializer.json_api_deserialization_visitor:
        class: 'Mango\Bundle\JsonApiBundle\Serializer\JsonApiDeserializationVisitor'
        arguments:
            - '@jms_serializer.naming_strategy'
        tags:
            - { name: 'jms_serializer.deserialization_visitor', format: 'json:api' }

    jms_serializer.json_api_constraint_violation_handler:
        class: 'Mango\Bundle\JsonApiBundle\Serializer\Handler\ConstraintViolationHandler'
        public: true
        tags:
            - { name: 'jms_serializer.subscribing_handler' }

    jms_serializer.json_api_exception_handler:
        class: 'Mango\Bundle\JsonApiBundle\Serializer\Handler\ExceptionHandler'
        public: true
        tags:
            - { name: 'jms_serializer.subscribing_handler' }

    json_api.exception.subscriber:
        class: 'Mango\Bundle\JsonApiBundle\EventListener\ExceptionSubscriber'
        public: true
        arguments:
            - '@jms_serializer'
            - '%json_api.catch_exceptions%'
        calls:
            - [ setLogger, ['@?logger'] ]
        tags:
            - { name: 'kernel.event_subscriber' }

    jms_serializer.handler_registry:
        class: 'Mango\Bundle\JsonApiBundle\Serializer\Handler\LazyRegexHandlerRegistry'
        arguments:
            - '@service_container'
